name: New problem

on:
  workflow_call:
    inputs:
      count:
        description: 'How many problems in this contest?'
        required: true
        type: number
      runs-on:
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  create:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - uses: TNFSH-Programming-Contest/tps-actions/.github/actions/install-tps@main
        if: ${{ runner.name == 'Hosted Agent' || startsWith(runner.name, 'GitHub Actions') }}

      - name: Download templates
        uses: actions/checkout@v3
        with:
          repository: 'TNFSH-Programming-Contest/tps-task-templates'
          path: 'tps-task-templates'

      - uses: TNFSH-Programming-Contest/tps-actions/.github/actions/new-problem@main
        with:
          problem-count: ${{ inputs.count }}

      - name: Commit and Push
        run: |
          git add .problems.json
          git add Makefile
          git add README.md
          git add _config.yml
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git diff --cached --quiet || git commit -m "Create ${{ inputs.count }} problems"
          git push
